media: files
content:
  - name: articles
    label: Articles
    type: collection
    path: content/articles
    subfolders: true
    fields:
    - { name: title, label: Title, type: string }
    - { name: category, label: category, type: string }
    - { name: excerpt, label: excerpt, type: string }
    - { name: body, label: Body, type: rich-text }